# External Secrets Operator Configuration for AWS Secrets Manager
apiVersion: external-secrets.io/v1beta1
kind: SecretStore
metadata:
  name: aws-secrets-manager
  namespace: austa-cockpit
  labels:
    app: austa-cockpit
    component: secrets
spec:
  provider:
    aws:
      service: SecretsManager
      region: us-east-1
      auth:
        secretRef:
          accessKeyID:
            name: aws-secret
            key: access-key-id
          secretAccessKey:
            name: aws-secret
            key: secret-access-key
---
# External Secret for Database Credentials
apiVersion: external-secrets.io/v1beta1
kind: ExternalSecret
metadata:
  name: austa-db-secrets
  namespace: austa-cockpit
  labels:
    app: austa-cockpit
    component: database
spec:
  refreshInterval: 1h
  secretStoreRef:
    name: aws-secrets-manager
    kind: SecretStore
  target:
    name: austa-db-secrets
    creationPolicy: Owner
    template:
      type: Opaque
      metadata:
        annotations:
          kubernetes.io/managed-by: external-secrets-operator
        labels:
          app: austa-cockpit
          component: database
  data:
  - secretKey: postgres-user
    remoteRef:
      key: austa-cockpit/database
      property: postgres_user
  - secretKey: postgres-password
    remoteRef:
      key: austa-cockpit/database
      property: postgres_password
  - secretKey: postgres-db
    remoteRef:
      key: austa-cockpit/database
      property: postgres_db
  - secretKey: redis-password
    remoteRef:
      key: austa-cockpit/database
      property: redis_password
  - secretKey: mongo-root-username
    remoteRef:
      key: austa-cockpit/database
      property: mongo_root_username
  - secretKey: mongo-root-password
    remoteRef:
      key: austa-cockpit/database
      property: mongo_root_password
---
# External Secret for API Keys
apiVersion: external-secrets.io/v1beta1
kind: ExternalSecret
metadata:
  name: austa-api-secrets
  namespace: austa-cockpit
  labels:
    app: austa-cockpit
    component: api
spec:
  refreshInterval: 1h
  secretStoreRef:
    name: aws-secrets-manager
    kind: SecretStore
  target:
    name: austa-api-secrets
    creationPolicy: Owner
    template:
      type: Opaque
      metadata:
        annotations:
          kubernetes.io/managed-by: external-secrets-operator
        labels:
          app: austa-cockpit
          component: api
  data:
  - secretKey: jwt-secret
    remoteRef:
      key: austa-cockpit/api
      property: jwt_secret
  - secretKey: session-secret
    remoteRef:
      key: austa-cockpit/api
      property: session_secret
  - secretKey: claude-api-key
    remoteRef:
      key: austa-cockpit/api
      property: claude_api_key
  - secretKey: anthropic-api-key
    remoteRef:
      key: austa-cockpit/api
      property: anthropic_api_key
---
# External Secret for AI Service
apiVersion: external-secrets.io/v1beta1
kind: ExternalSecret
metadata:
  name: austa-ai-secrets
  namespace: austa-cockpit
  labels:
    app: austa-cockpit
    component: ai-service
spec:
  refreshInterval: 1h
  secretStoreRef:
    name: aws-secrets-manager
    kind: SecretStore
  target:
    name: austa-ai-secrets
    creationPolicy: Owner
    template:
      type: Opaque
      metadata:
        annotations:
          kubernetes.io/managed-by: external-secrets-operator
        labels:
          app: austa-cockpit
          component: ai-service
  data:
  - secretKey: claude-api-key
    remoteRef:
      key: austa-cockpit/ai
      property: claude_api_key
  - secretKey: anthropic-api-key
    remoteRef:
      key: austa-cockpit/ai
      property: anthropic_api_key
  - secretKey: sentry-dsn
    remoteRef:
      key: austa-cockpit/ai
      property: sentry_dsn
---
# External Secret for AWS S3 Backup
apiVersion: external-secrets.io/v1beta1
kind: ExternalSecret
metadata:
  name: austa-backup-secrets
  namespace: austa-cockpit
  labels:
    app: austa-cockpit
    component: backup
spec:
  refreshInterval: 1h
  secretStoreRef:
    name: aws-secrets-manager
    kind: SecretStore
  target:
    name: austa-backup-secrets
    creationPolicy: Owner
    template:
      type: Opaque
      metadata:
        annotations:
          kubernetes.io/managed-by: external-secrets-operator
        labels:
          app: austa-cockpit
          component: backup
  data:
  - secretKey: aws-access-key-id
    remoteRef:
      key: austa-cockpit/backup
      property: aws_access_key_id
  - secretKey: aws-secret-access-key
    remoteRef:
      key: austa-cockpit/backup
      property: aws_secret_access_key
  - secretKey: s3-bucket
    remoteRef:
      key: austa-cockpit/backup
      property: s3_bucket