# Template for creating sealed secrets
# Use kubeseal to encrypt these secrets before committing to git
#
# Example usage:
# echo -n mypassword | kubectl create secret generic mysecret --dry-run=client --from-file=password=/dev/stdin -o yaml | kubeseal -o yaml > mysecret-sealed.yaml

---
# Database Secret Template
apiVersion: v1
kind: Secret
metadata:
  name: database-secret
  namespace: austa-cockpit-staging # Change namespace as needed
type: Opaque
stringData:
  url: "postgresql://username:password@host:5432/database"
  username: "austa"
  password: "REPLACE_WITH_ACTUAL_PASSWORD"
  host: "postgres-service"
  port: "5432"
  database: "austa_db"

---
# Redis Secret Template
apiVersion: v1
kind: Secret
metadata:
  name: redis-secret
  namespace: austa-cockpit-staging # Change namespace as needed
type: Opaque
stringData:
  url: "redis://:password@host:6379"
  password: "REPLACE_WITH_ACTUAL_PASSWORD"
  host: "redis-service"
  port: "6379"

---
# Application Secrets Template
apiVersion: v1
kind: Secret
metadata:
  name: app-secrets
  namespace: austa-cockpit-staging # Change namespace as needed
type: Opaque
stringData:
  jwt-secret: "REPLACE_WITH_ACTUAL_JWT_SECRET"
  claude-api-key: "REPLACE_WITH_ACTUAL_CLAUDE_API_KEY"
  openai-api-key: "REPLACE_WITH_ACTUAL_OPENAI_API_KEY"
  session-secret: "REPLACE_WITH_ACTUAL_SESSION_SECRET"
  encryption-key: "REPLACE_WITH_ACTUAL_ENCRYPTION_KEY"

---
# MongoDB Secret Template
apiVersion: v1
kind: Secret
metadata:
  name: mongodb-secret
  namespace: austa-cockpit-staging # Change namespace as needed
type: Opaque
stringData:
  url: "mongodb://username:password@host:27017/database"
  username: "austa"
  password: "REPLACE_WITH_ACTUAL_PASSWORD"
  host: "mongodb-service"
  port: "27017"
  database: "austa_logs"

---
# Docker Registry Secret Template
apiVersion: v1
kind: Secret
metadata:
  name: ghcr-secret
  namespace: austa-cockpit-staging # Change namespace as needed
type: kubernetes.io/dockerconfigjson
data:
  .dockerconfigjson: "REPLACE_WITH_BASE64_ENCODED_DOCKER_CONFIG"
# To generate:
# kubectl create secret docker-registry ghcr-secret \
#   --docker-server=ghcr.io \
#   --docker-username=USERNAME \
#   --docker-password=TOKEN \
#   --docker-email=EMAIL \
#   --dry-run=client -o yaml | kubeseal -o yaml