global:
  smtp_smarthost: 'mail.austa.com:587'
  smtp_from: 'alerts@austa.com'
  smtp_auth_username: 'alerts@austa.com'
  smtp_auth_password: 'your_smtp_password'
  
  slack_api_url: 'https://hooks.slack.com/services/YOUR/SLACK/WEBHOOK'
  
  # PagerDuty configuration
  pagerduty_url: 'https://events.pagerduty.com/v2/enqueue'

# Templates for alert notifications
templates:
  - '/etc/alertmanager/templates/*.tmpl'

# Routing configuration
route:
  group_by: ['alertname', 'service', 'severity']
  group_wait: 10s
  group_interval: 10s
  repeat_interval: 1h
  receiver: 'default-receiver'
  
  routes:
    # Critical alerts go to PagerDuty and Slack
    - match:
        severity: critical
      receiver: 'critical-alerts'
      group_wait: 5s
      repeat_interval: 30m
      
    # Security alerts
    - match:
        component: security
      receiver: 'security-team'
      group_wait: 5s
      repeat_interval: 15m
      
    # Business alerts go to business stakeholders
    - match:
        component: business
      receiver: 'business-team'
      group_wait: 30s
      repeat_interval: 2h
      
    # Infrastructure alerts
    - match:
        component: infrastructure
      receiver: 'ops-team'
      group_wait: 10s
      repeat_interval: 1h
      
    # Database alerts
    - match:
        component: database
      receiver: 'database-team'
      group_wait: 10s
      repeat_interval: 30m

# Inhibition rules
inhibit_rules:
  # Inhibit warning alerts if critical alert is firing
  - source_match:
      severity: 'critical'
    target_match:
      severity: 'warning'
    equal: ['alertname', 'service']
    
  # Inhibit service alerts if the service is down
  - source_match:
      alertname: 'ServiceDown'
    target_match_re:
      service: '.*'
    equal: ['service']

# Notification receivers
receivers:
  - name: 'default-receiver'
    email_configs:
      - to: 'admin@austa.com'
        subject: 'AUSTA Alert: {{ .GroupLabels.alertname }}'
        body: |
          {{ range .Alerts }}
          Alert: {{ .Annotations.summary }}
          Description: {{ .Annotations.description }}
          Service: {{ .Labels.service }}
          Severity: {{ .Labels.severity }}
          {{ end }}
        
  - name: 'critical-alerts'
    pagerduty_configs:
      - routing_key: 'YOUR_PAGERDUTY_INTEGRATION_KEY'
        description: 'AUSTA Critical Alert: {{ .GroupLabels.alertname }}'
        severity: 'critical'
        details:
          service: '{{ .GroupLabels.service }}'
          environment: 'production'
        links:
          - href: 'http://grafana:3001/d/austa-technical'
            text: 'Technical Dashboard'
          - href: 'http://kibana:5601'
            text: 'Logs Dashboard'
    
    slack_configs:
      - channel: '#austa-alerts-critical'
        title: 'AUSTA Critical Alert'
        text: |
          🚨 *Critical Alert Triggered* 🚨
          
          *Alert:* {{ .GroupLabels.alertname }}
          *Service:* {{ .GroupLabels.service }}
          *Severity:* {{ .GroupLabels.severity }}
          
          {{ range .Alerts }}
          *Summary:* {{ .Annotations.summary }}
          *Description:* {{ .Annotations.description }}
          {{ end }}
        color: 'danger'
        
    email_configs:
      - to: 'critical-alerts@austa.com'
        subject: '🚨 AUSTA CRITICAL: {{ .GroupLabels.alertname }}'
        body: |
          CRITICAL ALERT TRIGGERED
          
          {{ range .Alerts }}
          Alert: {{ .Annotations.summary }}
          Description: {{ .Annotations.description }}
          Service: {{ .Labels.service }}
          Time: {{ .StartsAt.Format "2006-01-02 15:04:05" }}
          {{ end }}
          
          Dashboard: http://grafana:3001/d/austa-technical
          Logs: http://kibana:5601

  - name: 'security-team'
    slack_configs:
      - channel: '#austa-security'
        title: 'AUSTA Security Alert'
        text: |
          🔒 *Security Alert* 🔒
          
          *Alert:* {{ .GroupLabels.alertname }}
          *Component:* {{ .GroupLabels.component }}
          
          {{ range .Alerts }}
          *Summary:* {{ .Annotations.summary }}
          *Description:* {{ .Annotations.description }}
          {{ end }}
        color: 'warning'
        
    email_configs:
      - to: 'security@austa.com'
        subject: '🔒 AUSTA Security Alert: {{ .GroupLabels.alertname }}'
        body: |
          SECURITY ALERT
          
          {{ range .Alerts }}
          Alert: {{ .Annotations.summary }}
          Description: {{ .Annotations.description }}
          Time: {{ .StartsAt.Format "2006-01-02 15:04:05" }}
          {{ end }}

  - name: 'business-team'
    slack_configs:
      - channel: '#austa-business'
        title: 'AUSTA Business Alert'
        text: |
          📊 *Business Metrics Alert* 📊
          
          *Alert:* {{ .GroupLabels.alertname }}
          
          {{ range .Alerts }}
          *Summary:* {{ .Annotations.summary }}
          *Description:* {{ .Annotations.description }}
          {{ end }}
        color: 'good'
        
    email_configs:
      - to: 'business@austa.com'
        subject: '📊 AUSTA Business Alert: {{ .GroupLabels.alertname }}'

  - name: 'ops-team'
    slack_configs:
      - channel: '#austa-ops'
        title: 'AUSTA Infrastructure Alert'
        text: |
          ⚙️ *Infrastructure Alert* ⚙️
          
          *Alert:* {{ .GroupLabels.alertname }}
          *Component:* {{ .GroupLabels.component }}
          
          {{ range .Alerts }}
          *Summary:* {{ .Annotations.summary }}
          *Description:* {{ .Annotations.description }}
          {{ end }}
        
    email_configs:
      - to: 'ops@austa.com'
        subject: '⚙️ AUSTA Infrastructure Alert: {{ .GroupLabels.alertname }}'

  - name: 'database-team'
    slack_configs:
      - channel: '#austa-database'
        title: 'AUSTA Database Alert'
        text: |
          🗄️ *Database Alert* 🗄️
          
          *Alert:* {{ .GroupLabels.alertname }}
          
          {{ range .Alerts }}
          *Summary:* {{ .Annotations.summary }}
          *Description:* {{ .Annotations.description }}
          {{ end }}
        color: 'warning'
        
    email_configs:
      - to: 'database@austa.com'
        subject: '🗄️ AUSTA Database Alert: {{ .GroupLabels.alertname }}'