# Service Accounts for AUSTA Cockpit components
apiVersion: v1
kind: ServiceAccount
metadata:
  name: austa-frontend-sa
  namespace: austa-cockpit
  labels:
    app: austa-cockpit
    component: frontend
automountServiceAccountToken: false
---
apiVersion: v1
kind: ServiceAccount
metadata:
  name: austa-backend-sa
  namespace: austa-cockpit
  labels:
    app: austa-cockpit
    component: backend
automountServiceAccountToken: true
---
apiVersion: v1
kind: ServiceAccount
metadata:
  name: austa-ai-service-sa
  namespace: austa-cockpit
  labels:
    app: austa-cockpit
    component: ai-service
automountServiceAccountToken: true
---
apiVersion: v1
kind: ServiceAccount
metadata:
  name: austa-database-sa
  namespace: austa-cockpit
  labels:
    app: austa-cockpit
    component: database
automountServiceAccountToken: false
---
apiVersion: v1
kind: ServiceAccount
metadata:
  name: austa-monitoring-sa
  namespace: austa-cockpit
  labels:
    app: austa-cockpit
    component: monitoring
automountServiceAccountToken: true
---
apiVersion: v1
kind: ServiceAccount
metadata:
  name: austa-backup-sa
  namespace: austa-cockpit
  labels:
    app: austa-cockpit
    component: backup
automountServiceAccountToken: true
---
# Service Account for security scanning
apiVersion: v1
kind: ServiceAccount
metadata:
  name: austa-security-scanner-sa
  namespace: austa-cockpit
  labels:
    app: austa-cockpit
    component: security
automountServiceAccountToken: true