groups:
- name: health_checks
  rules:
  - alert: ServiceDown
    expr: up{job=~"ai-service|backend-service|frontend-service"} == 0
    for: 1m
    labels:
      severity: critical
      team: platform
    annotations:
      summary: "Service {{ $labels.job }} is down"
      description: "Service {{ $labels.job }} has been down for more than 1 minute."
      runbook_url: "https://wiki.austa.com/runbooks/service-down"

  - alert: ServiceDegraded
    expr: health_check_status{status="degraded"} == 1
    for: 5m
    labels:
      severity: warning
      team: platform
    annotations:
      summary: "Service {{ $labels.job }} is degraded"
      description: "Service {{ $labels.job }} has been in degraded state for more than 5 minutes."

  - alert: HealthCheckResponseTimeSlow
    expr: health_check_duration_seconds > 5
    for: 2m
    labels:
      severity: warning
      team: platform
    annotations:
      summary: "Health check response time slow for {{ $labels.job }}"
      description: "Health check for {{ $labels.job }} is taking more than 5 seconds to respond."

  - alert: CircuitBreakerOpen
    expr: circuit_breaker_state == 2
    for: 1m
    labels:
      severity: critical
      team: platform
    annotations:
      summary: "Circuit breaker {{ $labels.circuit_breaker }} is open"
      description: "Circuit breaker {{ $labels.circuit_breaker }} in service {{ $labels.service }} has been open for more than 1 minute."

  - alert: DatabaseConnectionFailure
    expr: database_connection_health{status="unhealthy"} == 1
    for: 30s
    labels:
      severity: critical
      team: database
    annotations:
      summary: "Database connection failure in {{ $labels.service }}"
      description: "Database connection health check is failing in service {{ $labels.service }}."

  - alert: RedisConnectionFailure
    expr: redis_connection_health{status="unhealthy"} == 1
    for: 30s
    labels:
      severity: critical
      team: cache
    annotations:
      summary: "Redis connection failure in {{ $labels.service }}"
      description: "Redis connection health check is failing in service {{ $labels.service }}."

  - alert: AIModelNotLoaded
    expr: ai_model_loaded == 0
    for: 2m
    labels:
      severity: warning
      team: ai
    annotations:
      summary: "AI model {{ $labels.model_name }} not loaded"
      description: "AI model {{ $labels.model_name }} has not been loaded for more than 2 minutes."

  - alert: AIModelResponseTimeSlow
    expr: ai_model_response_time_seconds > 10
    for: 1m
    labels:
      severity: warning
      team: ai
    annotations:
      summary: "AI model {{ $labels.model_name }} response time slow"
      description: "AI model {{ $labels.model_name }} response time is above 10 seconds."

  - alert: ExternalDependencyDown
    expr: external_service_up == 0
    for: 2m
    labels:
      severity: warning
      team: platform
    annotations:
      summary: "External dependency {{ $labels.external_service }} is down"
      description: "External service {{ $labels.external_service }} has been unreachable for more than 2 minutes."

  - alert: HighSystemResourceUsage
    expr: cpu_usage_percent > 90 or memory_usage_percent > 90
    for: 5m
    labels:
      severity: warning
      team: platform
    annotations:
      summary: "High system resource usage in {{ $labels.job }}"
      description: "Service {{ $labels.job }} has high CPU or memory usage (>90%) for more than 5 minutes."

  - alert: CriticalSystemResourceUsage
    expr: cpu_usage_percent > 95 or memory_usage_percent > 95
    for: 2m
    labels:
      severity: critical
      team: platform
    annotations:
      summary: "Critical system resource usage in {{ $labels.job }}"
      description: "Service {{ $labels.job }} has critical CPU or memory usage (>95%) for more than 2 minutes."

  - alert: HealthCheckFailureRateHigh
    expr: rate(health_check_failures_total[5m]) > 0.1
    for: 2m
    labels:
      severity: warning
      team: platform
    annotations:
      summary: "High health check failure rate for {{ $labels.job }}"
      description: "Health check failure rate for {{ $labels.job }} is above 10% over the last 5 minutes."

  - alert: MultipleServicesDown
    expr: count(up{job=~"ai-service|backend-service|frontend-service"} == 0) >= 2
    for: 1m
    labels:
      severity: critical
      team: platform
    annotations:
      summary: "Multiple services are down"
      description: "{{ $value }} critical services are currently down."

  - alert: DatabaseConnectionPoolExhausted
    expr: database_connection_pool_active / database_connection_pool_max > 0.9
    for: 1m
    labels:
      severity: warning
      team: database
    annotations:
      summary: "Database connection pool nearly exhausted"
      description: "Database connection pool usage is above 90% for service {{ $labels.service }}."

  - alert: QueueBacklogHigh
    expr: queue_size > 1000
    for: 5m
    labels:
      severity: warning
      team: platform
    annotations:
      summary: "Queue backlog high for {{ $labels.queue_name }}"
      description: "Queue {{ $labels.queue_name }} has more than 1000 pending jobs for more than 5 minutes."

- name: consul_health
  rules:
  - alert: ConsulServiceDeregistered
    expr: consul_service_registered == 0
    for: 1m
    labels:
      severity: critical
      team: platform
    annotations:
      summary: "Service {{ $labels.service_name }} deregistered from Consul"
      description: "Service {{ $labels.service_name }} has been deregistered from Consul service discovery."

  - alert: ConsulHealthCheckCritical
    expr: consul_health_check_status{status="critical"} == 1
    for: 1m
    labels:
      severity: critical
      team: platform
    annotations:
      summary: "Consul health check critical for {{ $labels.service_name }}"
      description: "Consul health check for service {{ $labels.service_name }} is in critical state."

  - alert: ConsulClusterUnhealthy
    expr: consul_up == 0 or consul_raft_leader == 0
    for: 30s
    labels:
      severity: critical
      team: platform
    annotations:
      summary: "Consul cluster unhealthy"
      description: "Consul cluster is unhealthy - no leader or nodes are down."