global:
  scrape_interval: 15s
  evaluation_interval: 15s
  external_labels:
    monitor: 'austa-cockpit-monitor'
    environment: 'production'

rule_files:
  - "rules/*.yml"

alerting:
  alertmanagers:
    - static_configs:
        - targets:
          - alertmanager:9093

scrape_configs:
  # Prometheus self-monitoring
  - job_name: 'prometheus'
    static_configs:
      - targets: ['localhost:9090']

  # Node Exporter - System metrics
  - job_name: 'node-exporter'
    static_configs:
      - targets: ['node-exporter:9100']
    scrape_interval: 5s

  # cAdvisor - Container metrics
  - job_name: 'cadvisor'
    static_configs:
      - targets: ['cadvisor:8080']
    scrape_interval: 5s

  # AUSTA Backend API
  - job_name: 'austa-backend'
    static_configs:
      - targets: ['backend:8000']
    metrics_path: '/metrics'
    scrape_interval: 10s
    scrape_timeout: 5s

  # AUSTA AI Service
  - job_name: 'austa-ai-service'
    static_configs:
      - targets: ['ai-service:8001']
    metrics_path: '/metrics'
    scrape_interval: 10s
    scrape_timeout: 5s

  # AUSTA Frontend (if serving metrics)
  - job_name: 'austa-frontend'
    static_configs:
      - targets: ['frontend:3000']
    metrics_path: '/metrics'
    scrape_interval: 30s
    scrape_timeout: 10s

  # Redis metrics
  - job_name: 'redis'
    static_configs:
      - targets: ['redis-exporter:9121']
    scrape_interval: 10s

  # PostgreSQL metrics
  - job_name: 'postgres'
    static_configs:
      - targets: ['postgres-exporter:9187']
    scrape_interval: 10s

  # Custom Business Metrics
  - job_name: 'austa-business-metrics'
    static_configs:
      - targets: ['backend:8000']
    metrics_path: '/business-metrics'
    scrape_interval: 30s
    scrape_timeout: 10s

  # Security Metrics
  - job_name: 'austa-security-metrics'
    static_configs:
      - targets: ['backend:8000']
    metrics_path: '/security-metrics'
    scrape_interval: 60s
    scrape_timeout: 15s

  # Application Performance Monitoring
  - job_name: 'austa-apm'
    static_configs:
      - targets: ['backend:8000', 'ai-service:8001']
    metrics_path: '/apm-metrics'
    scrape_interval: 15s
    scrape_timeout: 10s

  # Fraud Detection Metrics
  - job_name: 'fraud-detection'
    static_configs:
      - targets: ['ai-service:8001']
    metrics_path: '/fraud-metrics'
    scrape_interval: 30s
    scrape_timeout: 10s

  # Case Processing Metrics
  - job_name: 'case-processing'
    static_configs:
      - targets: ['backend:8000']
    metrics_path: '/case-metrics'
    scrape_interval: 20s
    scrape_timeout: 10s