# Staging environment values
global:
  imageRegistry: ghcr.io
  imagePullSecrets: []

frontend:
  replicaCount: 2
  image:
    tag: main
  resources:
    limits:
      cpu: 300m
      memory: 256Mi
    requests:
      cpu: 50m
      memory: 64Mi
  autoscaling:
    enabled: false

backend:
  replicaCount: 2
  image:
    tag: main
  resources:
    limits:
      cpu: 500m
      memory: 512Mi
    requests:
      cpu: 100m
      memory: 256Mi
  autoscaling:
    enabled: false

aiService:
  replicaCount: 1
  image:
    tag: main
  resources:
    limits:
      cpu: 1000m
      memory: 2Gi
    requests:
      cpu: 200m
      memory: 512Mi
  autoscaling:
    enabled: false

ingress:
  hosts:
    - host: staging.austa-cockpit.com
      paths:
        - path: /
          pathType: Prefix
          service:
            name: frontend
            port: 80
        - path: /api
          pathType: Prefix
          service:
            name: backend
            port: 3000
        - path: /ai
          pathType: Prefix
          service:
            name: ai-service
            port: 8000
  tls:
    - secretName: staging-austa-cockpit-tls
      hosts:
        - staging.austa-cockpit.com

postgresql:
  primary:
    persistence:
      size: 10Gi
    resources:
      limits:
        cpu: 500m
        memory: 1Gi
      requests:
        cpu: 100m
        memory: 256Mi

redis:
  master:
    persistence:
      size: 4Gi
    resources:
      limits:
        cpu: 250m
        memory: 512Mi
      requests:
        cpu: 50m
        memory: 128Mi

mongodb:
  persistence:
    size: 8Gi
  resources:
    limits:
      cpu: 500m
      memory: 1Gi
    requests:
      cpu: 100m
      memory: 256Mi

backup:
  enabled: false

monitoring:
  enabled: true
  prometheus:
    enabled: true
  grafana:
    enabled: false