# Curator Configuration for AUSTA Cockpit Log Management

client:
  hosts:
    - http://elasticsearch:9200
  port: 9200
  url_prefix:
  use_ssl: False
  certificate:
  client_cert:
  client_key:
  ssl_no_validate: False
  username: elastic
  password: austa123
  timeout: 30
  master_only: False

logging:
  loglevel: INFO
  logfile: /var/log/curator/curator.log
  logformat: json
  blacklist: ['elasticsearch', 'urllib3']