apiVersion: v1
kind: Service
metadata:
  name: {{ include "austa-cockpit.fullname" . }}-frontend
  labels:
    {{- include "austa-cockpit.labels" . | nindent 4 }}
    app.kubernetes.io/component: frontend
spec:
  type: {{ .Values.frontend.service.type }}
  ports:
    - port: {{ .Values.frontend.service.port }}
      targetPort: {{ .Values.frontend.service.targetPort }}
      protocol: TCP
      name: http
  selector:
    {{- include "austa-cockpit.selectorLabels" . | nindent 4 }}
    app.kubernetes.io/component: frontend

---
apiVersion: v1
kind: Service
metadata:
  name: {{ include "austa-cockpit.fullname" . }}-backend
  labels:
    {{- include "austa-cockpit.labels" . | nindent 4 }}
    app.kubernetes.io/component: backend
  annotations:
    prometheus.io/scrape: "true"
    prometheus.io/port: "{{ .Values.backend.service.port }}"
    prometheus.io/path: "/api/metrics"
spec:
  type: {{ .Values.backend.service.type }}
  ports:
    - port: {{ .Values.backend.service.port }}
      targetPort: {{ .Values.backend.service.targetPort }}
      protocol: TCP
      name: http
  selector:
    {{- include "austa-cockpit.selectorLabels" . | nindent 4 }}
    app.kubernetes.io/component: backend

---
apiVersion: v1
kind: Service
metadata:
  name: {{ include "austa-cockpit.fullname" . }}-ai-service
  labels:
    {{- include "austa-cockpit.labels" . | nindent 4 }}
    app.kubernetes.io/component: ai-service
  annotations:
    prometheus.io/scrape: "true"
    prometheus.io/port: "{{ .Values.aiService.service.port }}"
    prometheus.io/path: "/api/v1/metrics"
spec:
  type: {{ .Values.aiService.service.type }}
  ports:
    - port: {{ .Values.aiService.service.port }}
      targetPort: {{ .Values.aiService.service.targetPort }}
      protocol: TCP
      name: http
  selector:
    {{- include "austa-cockpit.selectorLabels" . | nindent 4 }}
    app.kubernetes.io/component: ai-service